import { GroupSize } from "@/types/createNews";



export const categoryOptions = [
    { label: "News", value: "news"},
    { label: "Education", value: "education"},
    { label: "Technology", value: "technology"},
    { label: "Health", value: "health"},
    { label: "Entertainment", value: "entertainment"},
    { label: "Sports", value: "sports"},
    { label: "Politics", value: "politics"},
    { label: "Business", value: "business"},
    { label: "Science", value: "science"},
    { label: "Travel", value: "travel"},
    { label: "Others", value: "others"},
];

export const keywordOptions = [
    { label: "Technology", value: "Technology" },
    { label: "Health", value: "Health" },
    { label: "Fitness", value: "Fitness" },
    { label: "Food", value: "Food" },
    { label: "Recipes", value: "Recipes" },
    { label: "Travel", value: "Travel" },
    { label: "Lifestyle", value: "Lifestyle" },
    { label: "Fashion", value: "Fashion" },
    { label: "Beauty", value: "Beauty" },
    { label: "Parenting", value: "Parenting" },
    { label: "Business", value: "Business" },
    { label: "Finance", value: "Finance" },
    { label: "Investing", value: "Investing" },
    { label: "Education", value: "Education" },
    { label: "Science", value: "Science" },
    { label: "Environment", value: "Environment" },
    { label: "Politics", value: "Politics" },
    { label: "Entertainment", value: "Entertainment" },
    { label: "Music", value: "Music" },
    { label: "Movies", value: "Movies" },
    { label: "Sports", value: "Sports" },
    { label: "Gaming", value: "Gaming" },
    { label: "DIY", value: "DIY" },
    { label: "Crafts", value: "Crafts" },
    { label: "Home Improvement", value: "Home Improvement" },
    { label: "Real Estate", value: "Real Estate" },
    { label: "Pets", value: "Pets" },
    { label: "Automotive", value: "Automotive" },
    { label: "Career", value: "Career" },
    { label: "Relationships", value: "Relationships" },
    { label: "Digital Marketing", value: "Digital Marketing" },
    { label: "Social Media", value: "Social Media" },
    { label: "E-commerce", value: "E-commerce" },
    { label: "Online Shopping", value: "Online Shopping" },
    { label: "Web Development", value: "Web Development" },
    { label: "Machine Learning", value: "Machine Learning" },
    { label: "Artificial Intelligence", value: "Artificial Intelligence" },
    { label: "Data Science", value: "Data Science" },
    { label: "Cyber Security", value: "Cyber Security" },
    { label: "Cloud Computing", value: "Cloud Computing" },
    { label: "Virtual Reality", value: "Virtual Reality" },
    { label: "Augmented Reality", value: "Augmented Reality" },
    { label: "Internet of Things", value: "Internet of Things" },
    { label: "Personal Finance", value: "Personal Finance" },
    { label: "Mental Health", value: "Mental Health" },
    { label: "Sustainable Living", value: "Sustainable Living" },
    { label: "Renewable Energy", value: "Renewable Energy" },
    { label: "Climate Change", value: "Climate Change" },
    { label: "Veganism", value: "Veganism" },
    { label: "Plant-Based Diet", value: "Plant-Based Diet" },
    { label: "Mindfulness", value: "Mindfulness" },
    { label: "Yoga", value: "Yoga" },
    { label: "Meditation", value: "Meditation" },
    { label: "Remote Work", value: "Remote Work" },
    { label: "Freelancing", value: "Freelancing" },
    { label: "Startups", value: "Startups" },
    { label: "Entrepreneurship", value: "Entrepreneurship" },
    { label: "Investment Strategies", value: "Investment Strategies" },
    { label: "Cryptocurrency", value: "Cryptocurrency" },
    { label: "Blockchain", value: "Blockchain" },
    // Add mo
];